### ISSUE TITLE
Crowdmap downloads broken

### ISSUE THREAD

**Issue by keneanung** [vadi2/ire-mapping-script#2]
Looks like the vadisystems.com domain got suspended and as such, crowdmap updates break

**Comment by vadi2** [comment]
It'll get restated shortly.

**Comment by vadi2** [comment]
Do need a new place to host updates though.

**Comment by keneanung** [comment]
Would launchpad work? They seem to serve raw content via http...

**Comment by keneanung** [comment]
Or we could use ragit to transform Github https urls into http ones..

**Comment by vadi2** [comment]
The downloads are back online now.

Launchpad was used for vadi-m maps, but having to use a version control
client was a barrier to mappers - same issue faces github. ire mapper
initially  used pure Dropbox because it is super simple - just drop your
map file in, done. That kind of broke when all-https was enforced, so to
keep the ease of use, I've setup my server to mirror Dropbox and that's the
dependency that needs resolving now.
